name: Example Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create an issue
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"title": "New Issue", "body": "Issue created by workflow."}' \
            https://api.github.com/repos/${{ github.repository }}/issues
